FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Courses-app

Courses-app is a simple API allowing consumers to view polls and vote in them.

## Questions Collection [/course/]

### List All Questions [GET]

+ Response 200 (application/json)

[
    {
        "id": 1,
        "name": "EnglishZone",
        "description": "learn english",
        "category": 1,
        "logo": "logo.jpg",
        "contacts": [
            {
                "type": 3,
                "value": "aaizasoltonoeva@gmail.com"
            }
        ],
        "branches": [
            {
                "latitude": "56.66",
                "longitude": "23",
                "address": "street Manas,1"
            }
        ]
    },
    {
        "id": 2,
        "name": "Bilart",
        "description": "drowing courses",
        "category": 2,
        "logo": "logoo.jpg",
        "contacts": [
            {
                "type": 1,
                "value": "aaizasoltonoeva@gmail.com"
            }
        ],
        "branches": [
            {
                "latitude": "1.90",
                "longitude": "56.14",
                "address": "street Toktogul,7"
            }
        ]
    },
    {
        "id": 4,
        "name": "Bil",
        "description": "drowing courses",
        "category": 2,
        "logo": "logoo.jpg",
        "contacts": [
            {
                "type": 1,
                "value": "aaizasoltonoeva@gmail.com"
            }
        ],
        "branches": [
            {
                "latitude": "1.90",
                "longitude": "56.14",
                "address": "street Toktogul,7"
            }
        ]
    }
]

    
### Create a New Question [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

{
        "name": "Bil",
        "description": "drowing courses",
        "category": 2,
        "logo": "logoo.jpg",
        "contacts": [
            {
                "type": 1,
                "value": "aaizasoltonoeva@gmail.com"
            }
        ],
        "branches": [
            {
                "latitude": "1.90",
                "longitude": "56.14",
                "address": "street Toktogul,7"
            }
        ]
    }
+ Response 201 (application/json)

    + Headers

            Location: /course/

    + Body

{
    "id": 6,
    "name": "Bil",
    "description": "drowing courses",
    "category": 2,
    "logo": "logoo.jpg",
    "contacts": [
        {
            "type": 1,
            "value": "aaizasoltonoeva@gmail.com"
        }
    ],
    "branches": [
        {
            "latitude": "1.90",
            "longitude": "56.14",
            "address": "street Toktogul,7"
        }
    ]
}

## Question [/course/{course_id}]

+ Parameters
    + course_1 (1) - ID of the Question in the form of an integer

### View a Questions Detail [GET]

+ Response 200 (application/json)

{
    "id": 1,
    "name": "EnglishZone",
    "description": "learn english",
    "category": 1,
    "logo": "logo.jpg",
    "contacts": [
        {
            "type": 3,
            "value": "aaizasoltonoeva@gmail.com"
        }
    ],
    "branches": [
        {
            "latitude": "56.66",
            "longitude": "23",
            "address": "street Manas,1"
        }
    ]
}


## Question [/course/{course_6}]

+ Parameters
    + course_6 (6) - ID of the Question in the form of an integer

### Delete [DELETE]

+ Response 204